theme: jekyll-theme-cayman
title: ScriptLinkStandard
description: ScriptLinkStandard is a class library created by Rebekah Children's Services to help organizations extend their Netsmart myAvatar medical record solution. The class library is open source and available to use for free on NuGet.
